<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class YucatanMunicipios extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $registros = [
            ['nombre' => 'Abalá', 'clave_inegi' => '001', 'region' => 'VI. Influencia Metropolitana'],
            ['nombre' => 'Acanceh', 'clave_inegi' => '002', 'region' => 'VI. Influencia Metropolitana'],
            ['nombre' => 'Akil', 'clave_inegi' => '003', 'region' => 'VII. Sur'],
            ['nombre' => 'Baca', 'clave_inegi' => '004', 'region' => 'VI. Influencia Metropolitana'],
            ['nombre' => 'Bokobá', 'clave_inegi' => '005', 'region' => 'IV. Centro'],
            ['nombre' => 'Buctzotz', 'clave_inegi' => '006', 'region' => 'I. Litoral Oriente'],
            ['nombre' => 'Cacalchén', 'clave_inegi' => '007', 'region' => 'IV. Centro'],
            ['nombre' => 'Calotmul', 'clave_inegi' => '008', 'region' => 'II. Oriente'],
            ['nombre' => 'Cansahcab', 'clave_inegi' => '009', 'region' => 'III. Litoral Centro'],
            ['nombre' => 'Cantamayec', 'clave_inegi' => '010', 'region' => 'V. Centro Sur'],
            ['nombre' => 'Celestún', 'clave_inegi' => '011', 'region' => 'I. Poniente'],
            ['nombre' => 'Cenotillo', 'clave_inegi' => '012', 'region' => 'II. Oriente'],
            ['nombre' => 'Conkal', 'clave_inegi' => '013', 'region' => 'VI. Influencia Metropolitana'],
            ['nombre' => 'Cuncunul', 'clave_inegi' => '014', 'region' => 'II. Oriente'],
            ['nombre' => 'Cuzamá', 'clave_inegi' => '015', 'region' => 'IV. Centro'],
            ['nombre' => 'Chacsinkín', 'clave_inegi' => '016', 'region' => 'VII. Sur'],
            ['nombre' => 'Chankom', 'clave_inegi' => '017', 'region' => 'II. Oriente'],
            ['nombre' => 'Chapab', 'clave_inegi' => '018', 'region' => 'V. Centro Sur'],
            ['nombre' => 'Chemax', 'clave_inegi' => '019', 'region' => 'II. Oriente'],
            ['nombre' => 'Chicxulub Pueblo', 'clave_inegi' => '020', 'region' => 'VI. Influencia Metropolitana'],
            ['nombre' => 'Chichimilá', 'clave_inegi' => '021', 'region' => 'II. Oriente'],
            ['nombre' => 'Chikindzonot', 'clave_inegi' => '022', 'region' => 'II. Oriente'],
            ['nombre' => 'Chocholá', 'clave_inegi' => '023', 'region' => 'I. Poniente'],
            ['nombre' => 'Chumayel', 'clave_inegi' => '024', 'region' => 'V. Centro Sur'],
            ['nombre' => 'Dzan', 'clave_inegi' => '025', 'region' => 'VII. Sur'],
            ['nombre' => 'Dzemul', 'clave_inegi' => '026', 'region' => 'III. Litoral Centro'],
            ['nombre' => 'Dzidzantún', 'clave_inegi' => '027', 'region' => 'III. Litoral Centro'],
            ['nombre' => 'Dzilam de Bravo', 'clave_inegi' => '028', 'region' => 'III. Litoral Centro'],
            ['nombre' => 'Dzilam González', 'clave_inegi' => '029', 'region' => 'III. Litoral Centro'],
            ['nombre' => 'Dzitás', 'clave_inegi' => '030', 'region' => 'II. Oriente'],
            ['nombre' => 'Dzoncauich', 'clave_inegi' => '031', 'region' => 'III. Litoral Centro'],
            ['nombre' => 'Espita', 'clave_inegi' => '032', 'region' => 'II. Oriente'],
            ['nombre' => 'Halachó', 'clave_inegi' => '033', 'region' => 'I. Poniente'],
            ['nombre' => 'Hocabá', 'clave_inegi' => '034', 'region' => 'IV. Centro'],
            ['nombre' => 'Hoctún', 'clave_inegi' => '035', 'region' => 'IV. Centro'],
            ['nombre' => 'Homún', 'clave_inegi' => '036', 'region' => 'IV. Centro'],
            ['nombre' => 'Huhí', 'clave_inegi' => '037', 'region' => 'IV. Centro'],
            ['nombre' => 'Hunucmá', 'clave_inegi' => '038', 'region' => 'I. Poniente'],
            ['nombre' => 'Ixil', 'clave_inegi' => '039', 'region' => 'VI. Influencia Metropolitana'],
            ['nombre' => 'Izamal', 'clave_inegi' => '040', 'region' => 'IV. Centro'],
            ['nombre' => 'Kanasín', 'clave_inegi' => '041', 'region' => 'VI. Influencia Metropolitana'],
            ['nombre' => 'Kantunil', 'clave_inegi' => '042', 'region' => 'IV. Centro'],
            ['nombre' => 'Kaua', 'clave_inegi' => '043', 'region' => 'II. Oriente'],
            ['nombre' => 'Kinchil', 'clave_inegi' => '044', 'region' => 'I. Poniente'],
            ['nombre' => 'Kopomá', 'clave_inegi' => '045', 'region' => 'I. Poniente'],
            ['nombre' => 'Mama', 'clave_inegi' => '046', 'region' => 'V. Centro Sur'],
            ['nombre' => 'Maní', 'clave_inegi' => '047', 'region' => 'V. Centro Sur'],
            ['nombre' => 'Maxcanú', 'clave_inegi' => '048', 'region' => 'I. Poniente'],
            ['nombre' => 'Mayapán', 'clave_inegi' => '049', 'region' => 'V. Centro Sur'],
            ['nombre' => 'Mérida', 'clave_inegi' => '050', 'region' => 'VI. Influencia Metropolitana'],
            ['nombre' => 'Mocochá', 'clave_inegi' => '051', 'region' => 'VI. Influencia Metropolitana'],
            ['nombre' => 'Motul', 'clave_inegi' => '052', 'region' => 'IV. Centro'],
            ['nombre' => 'Muna', 'clave_inegi' => '053', 'region' => 'VII. Sur'],
            ['nombre' => 'Muxupip', 'clave_inegi' => '054', 'region' => 'IV. Centro'],
            ['nombre' => 'Opichén', 'clave_inegi' => '055', 'region' => 'I. Poniente'],
            ['nombre' => 'Oxkutzcab', 'clave_inegi' => '056', 'region' => 'VII. Sur'],
            ['nombre' => 'Panabá', 'clave_inegi' => '057', 'region' => 'I. Litoral Oriente'],
            ['nombre' => 'Peto', 'clave_inegi' => '058', 'region' => 'VII. Sur'],
            ['nombre' => 'Progreso', 'clave_inegi' => '059', 'region' => 'VI. Influencia Metropolitana'],
            ['nombre' => 'Quintana Roo', 'clave_inegi' => '060', 'region' => 'IV. Centro'],
            ['nombre' => 'Río Lagartos', 'clave_inegi' => '061', 'region' => 'I. Litoral Oriente'],
            ['nombre' => 'Sacalum', 'clave_inegi' => '062', 'region' => 'VII. Sur'],
            ['nombre' => 'Samahil', 'clave_inegi' => '063', 'region' => 'I. Poniente'],
            ['nombre' => 'Sanahcat', 'clave_inegi' => '064', 'region' => 'IV. Centro'],
            ['nombre' => 'San Felipe', 'clave_inegi' => '065', 'region' => 'I. Litoral Oriente'],
            ['nombre' => 'Santa Elena', 'clave_inegi' => '066', 'region' => 'VII. Sur'],
            ['nombre' => 'Seyé', 'clave_inegi' => '067', 'region' => 'IV. Centro'],
            ['nombre' => 'Sinanché', 'clave_inegi' => '068', 'region' => 'III. Litoral Centro'],
            ['nombre' => 'Sotuta', 'clave_inegi' => '069', 'region' => 'IV. Centro'],
            ['nombre' => 'Sucilá', 'clave_inegi' => '070', 'region' => 'I. Litoral Oriente'],
            ['nombre' => 'Tahmek', 'clave_inegi' => '071', 'region' => 'IV. Centro'],
            ['nombre' => 'Teabo', 'clave_inegi' => '072', 'region' => 'V. Centro Sur'],
            ['nombre' => 'Tecoh', 'clave_inegi' => '073', 'region' => 'VI. Influencia Metropolitana'],
            ['nombre' => 'Tekal de Venegas', 'clave_inegi' => '074', 'region' => 'IV. Centro'],
            ['nombre' => 'Tekantó', 'clave_inegi' => '075', 'region' => 'IV. Centro'],
            ['nombre' => 'Tekax', 'clave_inegi' => '076', 'region' => 'VII. Sur'],
            ['nombre' => 'Tekit', 'clave_inegi' => '077', 'region' => 'V. Centro Sur'],
            ['nombre' => 'Tekom', 'clave_inegi' => '078', 'region' => 'II. Oriente'],
            ['nombre' => 'Telchac Pueblo', 'clave_inegi' => '079', 'region' => 'III. Litoral Centro'],
            ['nombre' => 'Telchac Puerto', 'clave_inegi' => '080', 'region' => 'III. Litoral Centro'],
            ['nombre' => 'Temax', 'clave_inegi' => '081', 'region' => 'III. Litoral Centro'],
            ['nombre' => 'Temozón', 'clave_inegi' => '082', 'region' => 'II. Oriente'],
            ['nombre' => 'Tepakán', 'clave_inegi' => '083', 'region' => 'IV. Centro'],
            ['nombre' => 'Tetiz', 'clave_inegi' => '084', 'region' => 'I. Poniente'],
            ['nombre' => 'Teya', 'clave_inegi' => '085', 'region' => 'IV. Centro'],
            ['nombre' => 'Ticul', 'clave_inegi' => '086', 'region' => 'VII. Sur'],
            ['nombre' => 'Timucuy', 'clave_inegi' => '087', 'region' => 'VI. Influencia Metropolitana'],
            ['nombre' => 'Tinum', 'clave_inegi' => '088', 'region' => 'II. Oriente'],
            ['nombre' => 'Tixcacalcupul', 'clave_inegi' => '089', 'region' => 'II. Oriente'],
            ['nombre' => 'Tixkokob', 'clave_inegi' => '090', 'region' => 'VI. Influencia Metropolitana'],
            ['nombre' => 'Tixmehuac', 'clave_inegi' => '091', 'region' => 'VII. Sur'],
            ['nombre' => 'Tixpéhual', 'clave_inegi' => '092', 'region' => 'VI. Influencia Metropolitana'],
            ['nombre' => 'Tizimín', 'clave_inegi' => '093', 'region' => 'I. Litoral Oriente'],
            ['nombre' => 'Tunkás', 'clave_inegi' => '094', 'region' => 'II. Oriente'],
            ['nombre' => 'Tzucacab', 'clave_inegi' => '095', 'region' => 'VII. Sur'],
            ['nombre' => 'Uayma', 'clave_inegi' => '096', 'region' => 'II. Oriente'],
            ['nombre' => 'Ucú', 'clave_inegi' => '097', 'region' => 'VI. Influencia Metropolitana'],
            ['nombre' => 'Umán', 'clave_inegi' => '098', 'region' => 'VI. Influencia Metropolitana'],
            ['nombre' => 'Valladolid', 'clave_inegi' => '099', 'region' => 'II. Oriente'],
            ['nombre' => 'Xocchel', 'clave_inegi' => '100', 'region' => 'IV. Centro'],
            ['nombre' => 'Yaxcabá', 'clave_inegi' => '101', 'region' => 'II. Oriente'],
            ['nombre' => 'Yaxkukul', 'clave_inegi' => '102', 'region' => 'VI. Influencia Metropolitana'],
            ['nombre' => 'Yobaín', 'clave_inegi' => '103', 'region' => 'III. Litoral Centro'],
            ['nombre' => 'Chikindzonot', 'clave_inegi' => '104', 'region' => 'II. Oriente'],
            ['nombre' => 'San Felipe', 'clave_inegi' => '105', 'region' => 'I. Litoral Oriente'],
            ['nombre' => 'Santa Elena', 'clave_inegi' => '106', 'region' => 'VII. Sur']
        ];

        DB::table('municipios')->insert($registros);
    }
}